//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFirstMVCAppSCAGT
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MyDBJMAAEntities : DbContext
    {
        public MyDBJMAAEntities()
            : base("name=MyDBJMAAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AUDITTABLE> AUDITTABLEs { get; set; }
        public virtual DbSet<Course> Courses { get; set; }
        public virtual DbSet<DepartmentID> DepartmentIDs { get; set; }
        public virtual DbSet<EmpJimmy> EmpJimmies { get; set; }
        public virtual DbSet<EmpJinalTable> EmpJinalTables { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<Student_New> Student_New { get; set; }
        public virtual DbSet<User_Address> User_Address { get; set; }
        public virtual DbSet<UserCopy> UserCopies { get; set; }
        public virtual DbSet<AuditLog> AuditLogs { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserJMMY> UserJMMies { get; set; }
        public virtual DbSet<MyFirstView> MyFirstViews { get; set; }
        public virtual DbSet<View_20230603> View_20230603 { get; set; }
    
        [DbFunction("MyDBJMAAEntities", "GETTABLES")]
        public virtual IQueryable<GETTABLES_Result> GETTABLES()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GETTABLES_Result>("[MyDBJMAAEntities].[GETTABLES]()");
        }
    
        [DbFunction("MyDBJMAAEntities", "GETTABLES_Multi")]
        public virtual IQueryable<GETTABLES_Multi_Result> GETTABLES_Multi()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GETTABLES_Multi_Result>("[MyDBJMAAEntities].[GETTABLES_Multi]()");
        }
    
        [DbFunction("MyDBJMAAEntities", "MyTableValuedFunction")]
        public virtual IQueryable<MyTableValuedFunction_Result> MyTableValuedFunction(Nullable<int> a)
        {
            var aParameter = a.HasValue ?
                new ObjectParameter("a", a) :
                new ObjectParameter("a", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<MyTableValuedFunction_Result>("[MyDBJMAAEntities].[MyTableValuedFunction](@a)", aParameter);
        }
    
        [DbFunction("MyDBJMAAEntities", "MyTableValuedFunction1")]
        public virtual IQueryable<MyTableValuedFunction1_Result> MyTableValuedFunction1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<MyTableValuedFunction1_Result>("[MyDBJMAAEntities].[MyTableValuedFunction1]()");
        }
    
        public virtual ObjectResult<GetMultipleData_Result> GetMultipleData(Nullable<int> studentId)
        {
            var studentIdParameter = studentId.HasValue ?
                new ObjectParameter("studentId", studentId) :
                new ObjectParameter("studentId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetMultipleData_Result>("GetMultipleData", studentIdParameter);
        }
    
        public virtual ObjectResult<MyFirstSP_Result> MyFirstSP(Nullable<int> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MyFirstSP_Result>("MyFirstSP", userIdParameter);
        }
    
        public virtual int SP_GetData(string studentName, Nullable<int> courseId, string address)
        {
            var studentNameParameter = studentName != null ?
                new ObjectParameter("studentName", studentName) :
                new ObjectParameter("studentName", typeof(string));
    
            var courseIdParameter = courseId.HasValue ?
                new ObjectParameter("courseId", courseId) :
                new ObjectParameter("courseId", typeof(int));
    
            var addressParameter = address != null ?
                new ObjectParameter("address", address) :
                new ObjectParameter("address", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_GetData", studentNameParameter, courseIdParameter, addressParameter);
        }
    
        public virtual ObjectResult<SP_SaveEmployee_Result> SP_SaveEmployee(Nullable<int> userId, string action)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SaveEmployee_Result>("SP_SaveEmployee", userIdParameter, actionParameter);
        }
    
        public virtual int Sp_Transaction(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Transaction", idParameter);
        }
    }
}
